System.config({
  defaultJSExtensions: true,
  transpiler: "babel",
  babelOptions: {
    "stage": 2,
    "optional": [
      "runtime",
      "es7.decorators",
      "es7.classProperties"
    ]
  },
  paths: {
    "*": "dist/*",
    "npm:*": "jspm_packages/npm/*",
    "github:*": "jspm_packages/github/*"
  },
  bundles: {
    "app-bundle": [
      "github:aurelia/templating-resources@0.14.0",
      "github:aurelia/templating-resources@0.14.0/aurelia-templating-resources",
      "github:aurelia/templating-resources@0.14.0/compose",
      "github:aurelia/dependency-injection@0.9.2",
      "github:aurelia/task-queue@0.6.2",
      "github:aurelia/templating@0.14.4",
      "github:aurelia/task-queue@0.6.2/aurelia-task-queue",
      "github:aurelia/dependency-injection@0.9.2/aurelia-dependency-injection",
      "github:aurelia/templating@0.14.4/aurelia-templating",
      "npm:core-js@0.9.18",
      "github:aurelia/metadata@0.7.3",
      "github:aurelia/logging@0.6.4",
      "github:aurelia/path@0.8.1",
      "github:aurelia/loader@0.8.7",
      "github:aurelia/binding@0.8.6",
      "github:aurelia/logging@0.6.4/aurelia-logging",
      "github:aurelia/path@0.8.1/aurelia-path",
      "npm:core-js@0.9.18/index",
      "github:aurelia/metadata@0.7.3/aurelia-metadata",
      "github:aurelia/loader@0.8.7/aurelia-loader",
      "github:aurelia/binding@0.8.6/aurelia-binding",
      "npm:core-js@0.9.18/shim",
      "npm:core-js@0.9.18/modules/core.dict",
      "npm:core-js@0.9.18/modules/core.iter-helpers",
      "npm:core-js@0.9.18/modules/core.$for",
      "npm:core-js@0.9.18/modules/core.delay",
      "npm:core-js@0.9.18/modules/core.function.part",
      "npm:core-js@0.9.18/modules/core.object",
      "npm:core-js@0.9.18/modules/core.array.turn",
      "npm:core-js@0.9.18/modules/core.number.iterator",
      "npm:core-js@0.9.18/modules/core.number.math",
      "npm:core-js@0.9.18/modules/core.string.escape-html",
      "npm:core-js@0.9.18/modules/core.date",
      "npm:core-js@0.9.18/modules/core.global",
      "npm:core-js@0.9.18/modules/core.log",
      "npm:core-js@0.9.18/modules/$",
      "npm:core-js@0.9.18/modules/es5",
      "npm:core-js@0.9.18/modules/es6.symbol",
      "npm:core-js@0.9.18/modules/es6.object.assign",
      "npm:core-js@0.9.18/modules/es6.object.is",
      "npm:core-js@0.9.18/modules/es6.object.set-prototype-of",
      "npm:core-js@0.9.18/modules/es6.object.to-string",
      "npm:core-js@0.9.18/modules/es6.object.statics-accept-primitives",
      "npm:core-js@0.9.18/modules/es6.function.name",
      "npm:core-js@0.9.18/modules/es6.function.has-instance",
      "npm:core-js@0.9.18/modules/es6.number.constructor",
      "npm:core-js@0.9.18/modules/es6.number.statics",
      "npm:core-js@0.9.18/modules/es6.math",
      "npm:core-js@0.9.18/modules/es6.string.from-code-point",
      "npm:core-js@0.9.18/modules/es6.string.raw",
      "npm:core-js@0.9.18/modules/es6.string.iterator",
      "npm:core-js@0.9.18/modules/es6.string.code-point-at",
      "npm:core-js@0.9.18/modules/es6.string.ends-with",
      "npm:core-js@0.9.18/modules/es6.string.includes",
      "npm:core-js@0.9.18/modules/es6.string.repeat",
      "npm:core-js@0.9.18/modules/es6.string.starts-with",
      "npm:core-js@0.9.18/modules/es6.array.from",
      "npm:core-js@0.9.18/modules/es6.array.of",
      "npm:core-js@0.9.18/modules/es6.array.iterator",
      "npm:core-js@0.9.18/modules/es6.array.species",
      "npm:core-js@0.9.18/modules/es6.array.copy-within",
      "npm:core-js@0.9.18/modules/es6.array.fill",
      "npm:core-js@0.9.18/modules/es6.array.find",
      "npm:core-js@0.9.18/modules/es6.array.find-index",
      "npm:core-js@0.9.18/modules/es6.regexp",
      "npm:core-js@0.9.18/modules/es6.promise",
      "npm:core-js@0.9.18/modules/es6.map",
      "npm:core-js@0.9.18/modules/es6.set",
      "npm:core-js@0.9.18/modules/es6.weak-map",
      "npm:core-js@0.9.18/modules/es6.weak-set",
      "npm:core-js@0.9.18/modules/es6.reflect",
      "npm:core-js@0.9.18/modules/es7.array.includes",
      "npm:core-js@0.9.18/modules/es7.string.at",
      "npm:core-js@0.9.18/modules/es7.string.lpad",
      "npm:core-js@0.9.18/modules/es7.string.rpad",
      "npm:core-js@0.9.18/modules/es7.regexp.escape",
      "npm:core-js@0.9.18/modules/es7.object.get-own-property-descriptors",
      "npm:core-js@0.9.18/modules/es7.object.to-array",
      "npm:core-js@0.9.18/modules/es7.map.to-json",
      "npm:core-js@0.9.18/modules/es7.set.to-json",
      "npm:core-js@0.9.18/modules/js.array.statics",
      "npm:core-js@0.9.18/modules/web.timers",
      "npm:core-js@0.9.18/modules/web.immediate",
      "npm:core-js@0.9.18/modules/web.dom.iterable",
      "npm:core-js@0.9.18/modules/$.ctx",
      "npm:core-js@0.9.18/modules/$.def",
      "npm:core-js@0.9.18/modules/$.assign",
      "npm:core-js@0.9.18/modules/$.keyof",
      "npm:core-js@0.9.18/modules/$.uid",
      "npm:core-js@0.9.18/modules/$.assert",
      "npm:core-js@0.9.18/modules/$.iter",
      "npm:core-js@0.9.18/modules/$.for-of",
      "npm:core-js@0.9.18/modules/$.iter-call",
      "npm:core-js@0.9.18/modules/$.mix",
      "npm:core-js@0.9.18/modules/$.partial",
      "npm:core-js@0.9.18/modules/$.own-keys",
      "npm:core-js@0.9.18/modules/$.cof",
      "npm:core-js@0.9.18/modules/$.unscope",
      "npm:core-js@0.9.18/modules/$.iter-define",
      "npm:core-js@0.9.18/modules/$.invoke",
      "npm:core-js@0.9.18/modules/$.replacer",
      "npm:core-js@0.9.18/modules/$.fw",
      "github:jspm/nodelibs-process@0.1.1",
      "npm:core-js@0.9.18/modules/$.dom-create",
      "npm:core-js@0.9.18/modules/$.array-methods",
      "npm:core-js@0.9.18/modules/$.array-includes",
      "npm:core-js@0.9.18/modules/$.throws",
      "npm:core-js@0.9.18/modules/$.shared",
      "npm:core-js@0.9.18/modules/$.redef",
      "npm:core-js@0.9.18/modules/$.enum-keys",
      "npm:core-js@0.9.18/modules/$.get-names",
      "npm:core-js@0.9.18/modules/$.wks",
      "npm:core-js@0.9.18/modules/$.same",
      "npm:core-js@0.9.18/modules/$.set-proto",
      "npm:core-js@0.9.18/modules/$.string-at",
      "npm:core-js@0.9.18/modules/$.string-repeat",
      "npm:core-js@0.9.18/modules/$.iter-detect",
      "npm:core-js@0.9.18/modules/$.species",
      "npm:core-js@0.9.18/modules/$.task",
      "npm:core-js@0.9.18/modules/$.collection-strong",
      "npm:core-js@0.9.18/modules/$.collection",
      "npm:core-js@0.9.18/modules/$.collection-weak",
      "npm:core-js@0.9.18/modules/$.string-pad",
      "npm:core-js@0.9.18/modules/$.collection-to-json",
      "github:jspm/nodelibs-process@0.1.1/index",
      "npm:process@0.10.1",
      "npm:process@0.10.1/browser",
      "github:aurelia/templating-resources@0.14.0/with",
      "github:aurelia/templating-resources@0.14.0/if",
      "github:aurelia/templating-resources@0.14.0/show",
      "github:aurelia/templating-resources@0.14.0/repeat",
      "github:aurelia/templating-resources@0.14.0/sanitize-html",
      "github:aurelia/templating-resources@0.14.0/focus",
      "github:aurelia/templating-resources@0.14.0/replaceable",
      "github:aurelia/templating-resources@0.14.0/global-behavior",
      "github:aurelia/templating-resources@0.14.0/compile-spy",
      "github:aurelia/templating-resources@0.14.0/view-spy",
      "github:aurelia/templating-binding@0.14.0",
      "github:aurelia/templating-binding@0.14.0/aurelia-templating-binding",
      "github:aurelia/loader-default@0.9.5",
      "github:aurelia/loader-default@0.9.5/aurelia-loader-default",
      "github:aurelia/http-client@0.10.3",
      "github:aurelia/http-client@0.10.3/aurelia-http-client",
      "github:aurelia/framework@0.15.0",
      "github:aurelia/framework@0.15.0/aurelia-framework",
      "github:aurelia/bootstrapper@0.16.0",
      "github:aurelia/bootstrapper@0.16.0/aurelia-bootstrapper",
      "github:aurelia/logging-console@0.6.2",
      "github:aurelia/logging-console@0.6.2/aurelia-logging-console",
      "main",
      "config",
      "app",
      "npm:kyu-core@0.1.0",
      "npm:kyu-core@0.1.0/dist/main",
      "npm:babel-core@5.8.23/polyfill",
      "npm:kyu-core@0.1.0/dist/board",
      "npm:kyu-core@0.1.0/dist/card",
      "npm:kyu-core@0.1.0/dist/player",
      "npm:kyu-core@0.1.0/dist/game",
      "npm:babel-core@5.8.23/lib/polyfill",
      "npm:kyu-core@0.1.0/dist/uuid",
      "npm:core-js@1.1.3/shim",
      "npm:babel-runtime@5.8.20/regenerator/runtime",
      "npm:core-js@1.1.3/modules/es5",
      "npm:core-js@1.1.3/modules/es6.object.assign",
      "npm:core-js@1.1.3/modules/es6.object.is",
      "npm:core-js@1.1.3/modules/es6.symbol",
      "npm:core-js@1.1.3/modules/es6.object.set-prototype-of",
      "npm:core-js@1.1.3/modules/es6.object.to-string",
      "npm:core-js@1.1.3/modules/es6.object.freeze",
      "npm:core-js@1.1.3/modules/es6.object.prevent-extensions",
      "npm:core-js@1.1.3/modules/es6.object.seal",
      "npm:core-js@1.1.3/modules/es6.object.is-frozen",
      "npm:core-js@1.1.3/modules/es6.object.is-sealed",
      "npm:core-js@1.1.3/modules/es6.object.get-own-property-descriptor",
      "npm:core-js@1.1.3/modules/es6.object.is-extensible",
      "npm:core-js@1.1.3/modules/es6.object.get-prototype-of",
      "npm:core-js@1.1.3/modules/es6.object.keys",
      "npm:core-js@1.1.3/modules/es6.object.get-own-property-names",
      "npm:core-js@1.1.3/modules/es6.function.name",
      "npm:core-js@1.1.3/modules/es6.function.has-instance",
      "npm:core-js@1.1.3/modules/es6.number.constructor",
      "npm:core-js@1.1.3/modules/es6.number.is-finite",
      "npm:core-js@1.1.3/modules/es6.number.is-integer",
      "npm:core-js@1.1.3/modules/es6.number.epsilon",
      "npm:core-js@1.1.3/modules/es6.number.is-nan",
      "npm:core-js@1.1.3/modules/es6.number.is-safe-integer",
      "npm:core-js@1.1.3/modules/es6.number.max-safe-integer",
      "npm:core-js@1.1.3/modules/es6.number.min-safe-integer",
      "npm:core-js@1.1.3/modules/es6.number.parse-float",
      "npm:core-js@1.1.3/modules/es6.number.parse-int",
      "npm:core-js@1.1.3/modules/es6.math.acosh",
      "npm:core-js@1.1.3/modules/es6.math.asinh",
      "npm:core-js@1.1.3/modules/es6.math.atanh",
      "npm:core-js@1.1.3/modules/es6.math.cbrt",
      "npm:core-js@1.1.3/modules/es6.math.cosh",
      "npm:core-js@1.1.3/modules/es6.math.fround",
      "npm:core-js@1.1.3/modules/es6.math.clz32",
      "npm:core-js@1.1.3/modules/es6.math.hypot",
      "npm:core-js@1.1.3/modules/es6.math.imul",
      "npm:core-js@1.1.3/modules/es6.math.log10",
      "npm:core-js@1.1.3/modules/es6.math.log1p",
      "npm:core-js@1.1.3/modules/es6.math.expm1",
      "npm:core-js@1.1.3/modules/es6.math.log2",
      "npm:core-js@1.1.3/modules/es6.math.sign",
      "npm:core-js@1.1.3/modules/es6.math.tanh",
      "npm:core-js@1.1.3/modules/es6.math.sinh",
      "npm:core-js@1.1.3/modules/es6.math.trunc",
      "npm:core-js@1.1.3/modules/es6.string.from-code-point",
      "npm:core-js@1.1.3/modules/es6.string.raw",
      "npm:core-js@1.1.3/modules/es6.string.trim",
      "npm:core-js@1.1.3/modules/es6.string.iterator",
      "npm:core-js@1.1.3/modules/es6.string.code-point-at",
      "npm:core-js@1.1.3/modules/es6.string.includes",
      "npm:core-js@1.1.3/modules/es6.string.ends-with",
      "npm:core-js@1.1.3/modules/es6.string.repeat",
      "npm:core-js@1.1.3/modules/es6.string.starts-with",
      "npm:core-js@1.1.3/modules/es6.array.from",
      "npm:core-js@1.1.3/modules/es6.array.of",
      "npm:core-js@1.1.3/modules/es6.array.iterator",
      "npm:core-js@1.1.3/modules/es6.array.species",
      "npm:core-js@1.1.3/modules/es6.array.copy-within",
      "npm:core-js@1.1.3/modules/es6.array.fill",
      "npm:core-js@1.1.3/modules/es6.array.find",
      "npm:core-js@1.1.3/modules/es6.array.find-index",
      "npm:core-js@1.1.3/modules/es6.regexp.constructor",
      "npm:core-js@1.1.3/modules/es6.regexp.flags",
      "npm:core-js@1.1.3/modules/es6.regexp.replace",
      "npm:core-js@1.1.3/modules/es6.regexp.search",
      "npm:core-js@1.1.3/modules/es6.regexp.match",
      "npm:core-js@1.1.3/modules/es6.regexp.split",
      "npm:core-js@1.1.3/modules/es6.map",
      "npm:core-js@1.1.3/modules/es6.promise",
      "npm:core-js@1.1.3/modules/es6.set",
      "npm:core-js@1.1.3/modules/es6.weak-map",
      "npm:core-js@1.1.3/modules/es6.weak-set",
      "npm:core-js@1.1.3/modules/es6.reflect.apply",
      "npm:core-js@1.1.3/modules/es6.reflect.construct",
      "npm:core-js@1.1.3/modules/es6.reflect.define-property",
      "npm:core-js@1.1.3/modules/es6.reflect.delete-property",
      "npm:core-js@1.1.3/modules/es6.reflect.enumerate",
      "npm:core-js@1.1.3/modules/es6.reflect.get",
      "npm:core-js@1.1.3/modules/es6.reflect.get-own-property-descriptor",
      "npm:core-js@1.1.3/modules/es6.reflect.get-prototype-of",
      "npm:core-js@1.1.3/modules/es6.reflect.has",
      "npm:core-js@1.1.3/modules/es6.reflect.is-extensible",
      "npm:core-js@1.1.3/modules/es6.reflect.own-keys",
      "npm:core-js@1.1.3/modules/es6.reflect.prevent-extensions",
      "npm:core-js@1.1.3/modules/es6.reflect.set",
      "npm:core-js@1.1.3/modules/es6.reflect.set-prototype-of",
      "npm:core-js@1.1.3/modules/es7.string.at",
      "npm:core-js@1.1.3/modules/es7.array.includes",
      "npm:core-js@1.1.3/modules/es7.string.pad-left",
      "npm:core-js@1.1.3/modules/es7.string.pad-right",
      "npm:core-js@1.1.3/modules/es7.string.trim-left",
      "npm:core-js@1.1.3/modules/es7.string.trim-right",
      "npm:core-js@1.1.3/modules/es7.regexp.escape",
      "npm:core-js@1.1.3/modules/es7.object.get-own-property-descriptors",
      "npm:core-js@1.1.3/modules/es7.object.values",
      "npm:core-js@1.1.3/modules/es7.object.entries",
      "npm:core-js@1.1.3/modules/es7.map.to-json",
      "npm:core-js@1.1.3/modules/js.array.statics",
      "npm:core-js@1.1.3/modules/es7.set.to-json",
      "npm:core-js@1.1.3/modules/web.immediate",
      "npm:core-js@1.1.3/modules/web.timers",
      "npm:core-js@1.1.3/modules/web.dom.iterable",
      "npm:core-js@1.1.3/modules/$.core",
      "npm:babel-runtime@5.8.20/core-js/symbol",
      "npm:babel-runtime@5.8.20/core-js/symbol/iterator",
      "npm:babel-runtime@5.8.20/core-js/object/create",
      "npm:babel-runtime@5.8.20/core-js/promise",
      "npm:core-js@1.1.3/modules/$",
      "npm:core-js@1.1.3/modules/$.support-desc",
      "npm:core-js@1.1.3/modules/$.property-desc",
      "npm:core-js@1.1.3/modules/$.dom-create",
      "npm:core-js@1.1.3/modules/$.cof",
      "npm:core-js@1.1.3/modules/$.html",
      "npm:core-js@1.1.3/modules/$.has",
      "npm:core-js@1.1.3/modules/$.def",
      "npm:core-js@1.1.3/modules/$.invoke",
      "npm:core-js@1.1.3/modules/$.array-methods",
      "npm:core-js@1.1.3/modules/$.uid",
      "npm:core-js@1.1.3/modules/$.an-object",
      "npm:core-js@1.1.3/modules/$.is-object",
      "npm:core-js@1.1.3/modules/$.to-object",
      "npm:core-js@1.1.3/modules/$.to-iobject",
      "npm:core-js@1.1.3/modules/$.a-function",
      "npm:core-js@1.1.3/modules/$.to-integer",
      "npm:core-js@1.1.3/modules/$.to-index",
      "npm:core-js@1.1.3/modules/$.to-length",
      "npm:core-js@1.1.3/modules/$.iobject",
      "npm:core-js@1.1.3/modules/$.fails",
      "npm:core-js@1.1.3/modules/$.array-includes",
      "npm:core-js@1.1.3/modules/$.assign",
      "npm:core-js@1.1.3/modules/$.same",
      "npm:core-js@1.1.3/modules/$.global",
      "npm:core-js@1.1.3/modules/$.redef",
      "npm:core-js@1.1.3/modules/$.shared",
      "npm:core-js@1.1.3/modules/$.wks",
      "npm:core-js@1.1.3/modules/$.keyof",
      "npm:core-js@1.1.3/modules/$.tag",
      "npm:core-js@1.1.3/modules/$.get-names",
      "npm:core-js@1.1.3/modules/$.enum-keys",
      "npm:core-js@1.1.3/modules/$.library",
      "npm:core-js@1.1.3/modules/$.set-proto",
      "npm:core-js@1.1.3/modules/$.classof",
      "npm:core-js@1.1.3/modules/$.object-sap",
      "npm:core-js@1.1.3/modules/$.is-integer",
      "npm:core-js@1.1.3/modules/$.log1p",
      "npm:core-js@1.1.3/modules/$.sign",
      "npm:core-js@1.1.3/modules/$.expm1",
      "npm:core-js@1.1.3/modules/$.string-trim",
      "npm:core-js@1.1.3/modules/$.string-at",
      "npm:core-js@1.1.3/modules/$.iter-define",
      "npm:core-js@1.1.3/modules/$.string-context",
      "npm:core-js@1.1.3/modules/$.string-repeat",
      "npm:core-js@1.1.3/modules/$.ctx",
      "npm:core-js@1.1.3/modules/$.iter-call",
      "npm:core-js@1.1.3/modules/$.is-array-iter",
      "npm:core-js@1.1.3/modules/core.get-iterator-method",
      "npm:core-js@1.1.3/modules/$.iter-detect",
      "npm:core-js@1.1.3/modules/$.unscope",
      "npm:core-js@1.1.3/modules/$.iter-step",
      "npm:core-js@1.1.3/modules/$.iterators",
      "npm:core-js@1.1.3/modules/$.species",
      "npm:core-js@1.1.3/modules/$.flags",
      "npm:core-js@1.1.3/modules/$.fix-re-wks",
      "npm:core-js@1.1.3/modules/$.collection-strong",
      "npm:core-js@1.1.3/modules/$.collection",
      "npm:core-js@1.1.3/modules/$.strict-new",
      "npm:core-js@1.1.3/modules/$.for-of",
      "npm:core-js@1.1.3/modules/$.microtask",
      "npm:core-js@1.1.3/modules/$.mix",
      "npm:core-js@1.1.3/modules/$.collection-weak",
      "npm:core-js@1.1.3/modules/$.iter-create",
      "npm:core-js@1.1.3/modules/$.own-keys",
      "npm:core-js@1.1.3/modules/$.string-pad",
      "npm:core-js@1.1.3/modules/$.replacer",
      "npm:core-js@1.1.3/modules/$.object-to-array",
      "npm:core-js@1.1.3/modules/$.collection-to-json",
      "npm:core-js@1.1.3/modules/$.task",
      "npm:core-js@1.1.3/modules/$.partial",
      "npm:core-js@1.1.3/modules/$.hide",
      "npm:core-js@1.1.3/library/fn/symbol",
      "npm:core-js@1.1.3/library/fn/symbol/iterator",
      "npm:core-js@1.1.3/library/fn/object/create",
      "npm:core-js@1.1.3/library/fn/promise",
      "npm:core-js@1.1.3/modules/$.defined",
      "npm:core-js@1.1.3/modules/$.path",
      "npm:core-js@1.1.3/library/fn/symbol/index",
      "npm:core-js@1.1.3/library/modules/es6.string.iterator",
      "npm:core-js@1.1.3/library/modules/web.dom.iterable",
      "npm:core-js@1.1.3/library/modules/$.wks",
      "npm:core-js@1.1.3/library/modules/$",
      "npm:core-js@1.1.3/library/modules/es6.object.to-string",
      "npm:core-js@1.1.3/library/modules/es6.promise",
      "npm:core-js@1.1.3/library/modules/$.core",
      "npm:core-js@1.1.3/modules/$.iter-buggy",
      "npm:core-js@1.1.3/library/modules/$.string-at",
      "npm:core-js@1.1.3/library/modules/$.iter-define",
      "npm:core-js@1.1.3/library/modules/es6.symbol",
      "npm:core-js@1.1.3/library/modules/es6.array.iterator",
      "npm:core-js@1.1.3/library/modules/$.iterators",
      "npm:core-js@1.1.3/library/modules/$.shared",
      "npm:core-js@1.1.3/library/modules/$.global",
      "npm:core-js@1.1.3/library/modules/$.uid",
      "npm:core-js@1.1.3/library/modules/$.library",
      "npm:core-js@1.1.3/library/modules/$.ctx",
      "npm:core-js@1.1.3/library/modules/$.classof",
      "npm:core-js@1.1.3/library/modules/$.def",
      "npm:core-js@1.1.3/library/modules/$.is-object",
      "npm:core-js@1.1.3/library/modules/$.an-object",
      "npm:core-js@1.1.3/library/modules/$.a-function",
      "npm:core-js@1.1.3/library/modules/$.strict-new",
      "npm:core-js@1.1.3/library/modules/$.for-of",
      "npm:core-js@1.1.3/library/modules/$.set-proto",
      "npm:core-js@1.1.3/library/modules/$.same",
      "npm:core-js@1.1.3/library/modules/$.species",
      "npm:core-js@1.1.3/library/modules/$.microtask",
      "npm:core-js@1.1.3/library/modules/$.support-desc",
      "npm:core-js@1.1.3/library/modules/$.mix",
      "npm:core-js@1.1.3/library/modules/$.iter-detect",
      "npm:core-js@1.1.3/library/modules/$.tag",
      "npm:core-js@1.1.3/library/modules/$.to-integer",
      "npm:core-js@1.1.3/library/modules/$.has",
      "npm:core-js@1.1.3/library/modules/$.redef",
      "npm:core-js@1.1.3/library/modules/$.hide",
      "npm:core-js@1.1.3/library/modules/$.iter-create",
      "npm:core-js@1.1.3/library/modules/$.defined",
      "npm:core-js@1.1.3/library/modules/$.iter-buggy",
      "npm:core-js@1.1.3/library/modules/$.to-iobject",
      "npm:core-js@1.1.3/library/modules/$.enum-keys",
      "npm:core-js@1.1.3/library/modules/$.keyof",
      "npm:core-js@1.1.3/library/modules/$.fails",
      "npm:core-js@1.1.3/library/modules/$.get-names",
      "npm:core-js@1.1.3/library/modules/$.property-desc",
      "npm:core-js@1.1.3/library/modules/$.unscope",
      "npm:core-js@1.1.3/library/modules/$.iter-step",
      "npm:core-js@1.1.3/library/modules/$.cof",
      "npm:core-js@1.1.3/library/modules/$.is-array-iter",
      "npm:core-js@1.1.3/library/modules/$.iter-call",
      "npm:core-js@1.1.3/library/modules/$.to-length",
      "npm:core-js@1.1.3/library/modules/core.get-iterator-method",
      "npm:core-js@1.1.3/library/modules/$.task",
      "npm:core-js@1.1.3/library/modules/$.invoke",
      "npm:core-js@1.1.3/library/modules/$.dom-create",
      "npm:core-js@1.1.3/library/modules/$.iobject",
      "npm:core-js@1.1.3/library/modules/$.html"
    ]
  },

  map: {
    "aurelia-binding": "github:aurelia/binding@0.8.6",
    "aurelia-bootstrapper": "github:aurelia/bootstrapper@0.16.0",
    "aurelia-framework": "github:aurelia/framework@0.15.0",
    "aurelia-http-client": "github:aurelia/http-client@0.10.3",
    "aurelia-loader-default": "github:aurelia/loader-default@0.9.5",
    "aurelia-templating-binding": "github:aurelia/templating-binding@0.14.0",
    "aurelia-templating-resources": "github:aurelia/templating-resources@0.14.0",
    "babel": "npm:babel-core@5.8.23",
    "babel-runtime": "npm:babel-runtime@5.8.20",
    "core-js": "npm:core-js@1.1.3",
    "kyu-core": "npm:kyu-core@0.1.0",
    "github:aurelia/binding@0.8.6": {
      "aurelia-dependency-injection": "github:aurelia/dependency-injection@0.9.2",
      "aurelia-metadata": "github:aurelia/metadata@0.7.3",
      "aurelia-task-queue": "github:aurelia/task-queue@0.6.2",
      "core-js": "npm:core-js@0.9.18"
    },
    "github:aurelia/bootstrapper@0.16.0": {
      "aurelia-event-aggregator": "github:aurelia/event-aggregator@0.7.0",
      "aurelia-framework": "github:aurelia/framework@0.15.0",
      "aurelia-history": "github:aurelia/history@0.6.1",
      "aurelia-history-browser": "github:aurelia/history-browser@0.7.0",
      "aurelia-loader-default": "github:aurelia/loader-default@0.9.5",
      "aurelia-logging-console": "github:aurelia/logging-console@0.6.2",
      "aurelia-router": "github:aurelia/router@0.11.0",
      "aurelia-templating": "github:aurelia/templating@0.14.4",
      "aurelia-templating-binding": "github:aurelia/templating-binding@0.14.0",
      "aurelia-templating-resources": "github:aurelia/templating-resources@0.14.0",
      "aurelia-templating-router": "github:aurelia/templating-router@0.15.0",
      "core-js": "npm:core-js@0.9.18"
    },
    "github:aurelia/dependency-injection@0.9.2": {
      "aurelia-logging": "github:aurelia/logging@0.6.4",
      "aurelia-metadata": "github:aurelia/metadata@0.7.3",
      "core-js": "npm:core-js@0.9.18"
    },
    "github:aurelia/event-aggregator@0.7.0": {
      "aurelia-logging": "github:aurelia/logging@0.6.4"
    },
    "github:aurelia/framework@0.15.0": {
      "aurelia-binding": "github:aurelia/binding@0.8.6",
      "aurelia-dependency-injection": "github:aurelia/dependency-injection@0.9.2",
      "aurelia-loader": "github:aurelia/loader@0.8.7",
      "aurelia-logging": "github:aurelia/logging@0.6.4",
      "aurelia-metadata": "github:aurelia/metadata@0.7.3",
      "aurelia-path": "github:aurelia/path@0.8.1",
      "aurelia-task-queue": "github:aurelia/task-queue@0.6.2",
      "aurelia-templating": "github:aurelia/templating@0.14.4",
      "core-js": "npm:core-js@0.9.18"
    },
    "github:aurelia/history-browser@0.7.0": {
      "aurelia-history": "github:aurelia/history@0.6.1",
      "core-js": "npm:core-js@0.9.18"
    },
    "github:aurelia/http-client@0.10.3": {
      "aurelia-path": "github:aurelia/path@0.8.1",
      "core-js": "npm:core-js@0.9.18"
    },
    "github:aurelia/loader-default@0.9.5": {
      "aurelia-loader": "github:aurelia/loader@0.8.7",
      "aurelia-metadata": "github:aurelia/metadata@0.7.3"
    },
    "github:aurelia/loader@0.8.7": {
      "aurelia-html-template-element": "github:aurelia/html-template-element@0.2.0",
      "aurelia-metadata": "github:aurelia/metadata@0.7.3",
      "aurelia-path": "github:aurelia/path@0.8.1",
      "core-js": "npm:core-js@0.9.18",
      "webcomponentsjs": "github:webcomponents/webcomponentsjs@0.6.3"
    },
    "github:aurelia/logging-console@0.6.2": {
      "aurelia-logging": "github:aurelia/logging@0.6.4"
    },
    "github:aurelia/metadata@0.7.3": {
      "core-js": "npm:core-js@0.9.18"
    },
    "github:aurelia/route-recognizer@0.6.2": {
      "core-js": "npm:core-js@0.9.18"
    },
    "github:aurelia/router@0.11.0": {
      "aurelia-dependency-injection": "github:aurelia/dependency-injection@0.9.2",
      "aurelia-event-aggregator": "github:aurelia/event-aggregator@0.7.0",
      "aurelia-history": "github:aurelia/history@0.6.1",
      "aurelia-logging": "github:aurelia/logging@0.6.4",
      "aurelia-path": "github:aurelia/path@0.8.1",
      "aurelia-route-recognizer": "github:aurelia/route-recognizer@0.6.2",
      "core-js": "npm:core-js@0.9.18"
    },
    "github:aurelia/templating-binding@0.14.0": {
      "aurelia-binding": "github:aurelia/binding@0.8.6",
      "aurelia-logging": "github:aurelia/logging@0.6.4",
      "aurelia-templating": "github:aurelia/templating@0.14.4"
    },
    "github:aurelia/templating-resources@0.14.0": {
      "aurelia-binding": "github:aurelia/binding@0.8.6",
      "aurelia-dependency-injection": "github:aurelia/dependency-injection@0.9.2",
      "aurelia-logging": "github:aurelia/logging@0.6.4",
      "aurelia-task-queue": "github:aurelia/task-queue@0.6.2",
      "aurelia-templating": "github:aurelia/templating@0.14.4",
      "core-js": "npm:core-js@0.9.18"
    },
    "github:aurelia/templating-router@0.15.0": {
      "aurelia-dependency-injection": "github:aurelia/dependency-injection@0.9.2",
      "aurelia-metadata": "github:aurelia/metadata@0.7.3",
      "aurelia-path": "github:aurelia/path@0.8.1",
      "aurelia-router": "github:aurelia/router@0.11.0",
      "aurelia-templating": "github:aurelia/templating@0.14.4"
    },
    "github:aurelia/templating@0.14.4": {
      "aurelia-binding": "github:aurelia/binding@0.8.6",
      "aurelia-dependency-injection": "github:aurelia/dependency-injection@0.9.2",
      "aurelia-html-template-element": "github:aurelia/html-template-element@0.2.0",
      "aurelia-loader": "github:aurelia/loader@0.8.7",
      "aurelia-logging": "github:aurelia/logging@0.6.4",
      "aurelia-metadata": "github:aurelia/metadata@0.7.3",
      "aurelia-path": "github:aurelia/path@0.8.1",
      "aurelia-task-queue": "github:aurelia/task-queue@0.6.2",
      "core-js": "npm:core-js@0.9.18"
    },
    "github:jspm/nodelibs-process@0.1.1": {
      "process": "npm:process@0.10.1"
    },
    "npm:babel-runtime@5.8.20": {
      "process": "github:jspm/nodelibs-process@0.1.1"
    },
    "npm:core-js@0.9.18": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "process": "github:jspm/nodelibs-process@0.1.1",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:core-js@1.1.3": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "process": "github:jspm/nodelibs-process@0.1.1",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    }
  }
});
